WITH
SALES_INFO AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE '2022-01-01' <= SALES_DATE AND SALES_DATE <= '2022-01-31'
    GROUP BY BOOK_ID
),
AUTHOR_INFO AS (
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.AUTHOR_NAME, B.PRICE
    FROM BOOK B
    JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
)
SELECT
    AI.AUTHOR_ID,
    AI.AUTHOR_NAME,
    AI.CATEGORY,
    SUM(SI.SALES * AI.PRICE) AS TOTAL_SALES
FROM SALES_INFO SI
JOIN AUTHOR_INFO AI ON SI.BOOK_ID = AI.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC