SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE OS
JOIN
    PRODUCT P ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    SALES DESC, P.PRODUCT_CODE