WITH USERS AS (
    SELECT COUNT(USER_ID) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) MONTH,
    COUNT(DISTINCT UI.USER_ID) AS PURCHASE_USERS,
    ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT CNT FROM USERS), 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE OS
JOIN
    USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE
    YEAR(UI.JOINED) = 2021
GROUP BY
    YEAR, MONTH
ORDER BY
    YEAR, MONTH