WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, B.GENERATION + 1
    FROM ECOLI_DATA A
    JOIN ECOLI_GENERATION B ON A.PARENT_ID = B.ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM ECOLI_GENERATION
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION