SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM
    FOOD_ORDER FO
JOIN
    FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID 
WHERE
    PRODUCE_DATE LIKE '2022-05-%'
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC