WITH TOTAL_SALES AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT * FROM FIRST_HALF
        UNION ALL
        SELECT * FROM JULY
    ) TOTAL
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM TOTAL_SALES
ORDER BY TOTAL_ORDER DESC
LIMIT 3
