SELECT
    DISTINCT(CRCC.CAR_ID)
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE
    MONTH(CRCRH.START_DATE) = 10 AND CRCC.CAR_TYPE = '세단'
ORDER BY
    CRCC.CAR_ID DESC