SELECT
    SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM
    HR_GRADE HG
JOIN
    HR_EMPLOYEES HE ON HE.EMP_NO = HG.EMP_NO
GROUP BY
    HG.EMP_NO
ORDER BY
    SUM(SCORE) DESC
LIMIT 1